### ISSUE TITLE
Strange effect fr version parcours page

### ISSUE THREAD

**Issue by pflammarion** [HipppB/Portfolio#3]
Hello, ici on remarque que l'effet d'avant commence alors qu'on veut changer de page : cf la video ci dessous

https://user-images.githubusercontent.com/80546510/176456258-8790c37b-2501-412f-ab75-c41db78bcd0a.mov

**Comment by HipppB** [comment]
Wooow j'avais vraiment fait cette animation n'importe comment, c'est fix, merci
